name: Sync
on:
  push:
    branchs:
    - gh-pages
jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
    - run: mkdir -p ~/.ssh && echo "${{ secrets.GITEE_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    - run: git push --mirror git@gitee.com:OhYee/blotter_page.git