name: Sync
on:
  push:
    branchs:
    - gh-pages
jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
    - run: sudo mkdir -p /root/.ssh && sudo echo " ${{ secrets.GITEE_PRIVATE_KEY }}" > /root/.ssh/id_rsa && sudo chmod 600 /root/.ssh/id_rsa
    - run: git push --mirror git@gitee.com:OhYee/blotter_page.git