name: Sync
on:
  push:
    branchs:
      - gh-pages
jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Sync to gitee
      uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url: git@gitee.com:OhYee/blotter_page.git
        ssh_private_key: ${{ secrets.GITEE_PRIVATE_KEY }}