name: Sync
on:
  push:
    branchs:
      - gh-pages
jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Gitee
      uses: wearerequired/git-mirror-action@master
      env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
      with:
          source-repo: "git@github.com:OhYee/blotter_page.git"
          destination-repo: "git@gitee.com:OhYee/blotter_page.git"